/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerGame;
import Controller.ControllerHover;
import javax.swing.JButton;
import Models.partie.Partie;
import Style.Font.CustomFont;
import Style.Font.FontLoader;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author p1706110
 */
public class Game extends javax.swing.JPanel {

    private Window win;
    private Partie partie;
    private Window windowReplay;
    
    private ArrayList<JButton> listeBoutonsJeu;
    
    private Font origami28;
    private Font pencil22;
    private Font pencil28;
    private Font pencil32;
    /**
     * Creates new form Game
     * @param win
     * @param partie
     */
    public Game(Window win, Partie partie) {
        this.win = win;
        this.partie = partie;
        origami28 = new FontLoader().loadFont(CustomFont.ORIGAMI, 28);
        pencil22 = new FontLoader().loadFont(CustomFont.PENCIL, 22);
        pencil28 = new FontLoader().loadFont(CustomFont.PENCIL, 28);
        pencil32 = new FontLoader().loadFont(CustomFont.PENCIL, 32);
        initComponents();
        loadBoutonsJeu();
        jLabel1.setText(this.partie.getJoueur1());
        jLabel2.setText(this.partie.getJoueur2());
        jLabel3.setText(""+this.partie.getScoreJoueur1());
        jLabel4.setText(""+this.partie.getScoreJoueur2());
        jButton2.addActionListener(new ControllerGame(this));
        jButton3.addActionListener(new ControllerGame(this));
        jButton4.addActionListener(new ControllerGame(this));
        jButton3.addMouseListener(new ControllerHover(pencil22, pencil28));
        jButton2.addMouseListener(new ControllerHover(pencil22, pencil28));
        jButton4.addMouseListener(new ControllerHover(pencil22, pencil28));
        setListenersBoutonsJeu();
        
    }
    
    public Window getWindowReplay(){
        return windowReplay;
    }
    
    public void setReplayWindow(Window replayWindow){
        this.windowReplay = replayWindow;
    }
    
    public void setWindowReplay(Window windowReplay){
        this.windowReplay = windowReplay;
    }
    
    private void loadBoutonsJeu(){
        listeBoutonsJeu = new ArrayList<>();
        listeBoutonsJeu.add(jButton1);
        listeBoutonsJeu.add(jButton6);
        listeBoutonsJeu.add(jButton5);
        listeBoutonsJeu.add(jButton7);
        listeBoutonsJeu.add(jButton9);
        listeBoutonsJeu.add(jButton8);
        listeBoutonsJeu.add(jButton10);
        listeBoutonsJeu.add(jButton12);
        listeBoutonsJeu.add(jButton11);
        
        for(int i = 0; i<9;i++){
            int valCase = partie.getGrille().getCase(i%3, i/3).getContenu();
            if(valCase == 1){
                listeBoutonsJeu.get(i).setIcon( new ImageIcon(getClass().getResource("/Style/img/cercle.png")));
            }else if(valCase == 2){
                listeBoutonsJeu.get(i).setIcon( new ImageIcon(getClass().getResource("/Style/img/croix.png")));
            }
        }
    }
    
    private void setListenersBoutonsJeu(){
        for(int i = 0 ; i < listeBoutonsJeu.size(); i++){
            listeBoutonsJeu.get(i).addActionListener(new ControllerGame(this,i));
        }
    }
    
    public void nouvelleManche(Partie partie){
        for(JButton boutonJeu : listeBoutonsJeu){
            boutonJeu.setIcon(null);
        }
        jLabel3.setText(""+partie.getScoreJoueur1());
        jLabel4.setText(""+partie.getScoreJoueur2());
    }
   
    
    public ArrayList<JButton> getListeBoutonsJeu(){
        return listeBoutonsJeu;
    }

    public Window getWin() {
        return win;
    }

    public Partie getPartie() {
        return partie;
    }
    
    public JButton getjButton2() {
        return jButton2;
    }

    public JButton getjButton3() {
        return jButton3;
    }
    
    public JButton getjButton4() {
        return jButton4;
    }
    
    public void setLabelNomJoueurTour(String nomJoueur){
        jLabel5.setText("Au tour de "+nomJoueur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(null);

        jLabel1.setFont(pencil32);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nom Joueur 1");
        add(jLabel1);
        jLabel1.setBounds(10, 10, 200, 50);

        jLabel2.setFont(pencil32);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nom Joueur 2");
        add(jLabel2);
        jLabel2.setBounds(300, 10, 190, 50);

        jLabel3.setFont(origami28);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("0");
        add(jLabel3);
        jLabel3.setBounds(9, 59, 80, 80);

        jLabel4.setFont(origami28);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("0");
        add(jLabel4);
        jLabel4.setBounds(409, 59, 80, 80);

        jLabel5.setFont(pencil28);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Au tour de " + getPartie().getJoueur1());
        add(jLabel5);
        jLabel5.setBounds(132, 46, 240, 40);

        jButton2.setFont(pencil22);
        jButton2.setText("Replay");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(190, 330, 130, 45);

        jButton3.setFont(pencil22);
        jButton3.setText("Quitter");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(500, 400));
        add(jButton3);
        jButton3.setBounds(0, 330, 180, 45);

        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        add(jButton1);
        jButton1.setBounds(135, 82, 75, 75);

        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        add(jButton5);
        jButton5.setBounds(297, 82, 75, 75);

        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        add(jButton6);
        jButton6.setBounds(216, 82, 75, 75);

        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        add(jButton7);
        jButton7.setBounds(135, 163, 75, 75);

        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        add(jButton8);
        jButton8.setBounds(297, 163, 75, 75);

        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        add(jButton9);
        jButton9.setBounds(216, 163, 75, 75);

        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        add(jButton10);
        jButton10.setBounds(135, 244, 75, 75);

        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        add(jButton11);
        jButton11.setBounds(297, 244, 75, 75);

        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        add(jButton12);
        jButton12.setBounds(216, 244, 75, 75);

        jButton4.setFont(pencil22);
        jButton4.setText("Sauvegarder");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        add(jButton4);
        jButton4.setBounds(330, 330, 170, 45);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Style/img/papierJeu.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, -10, 500, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
