/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHover;
import Style.Font.CustomFont;
import Style.Font.FontLoader;
import Style.Sound.CustomSound;
import Style.Sound.SoundPlayer;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javafx.beans.InvalidationListener;
import javafx.beans.Observable;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author p1706110
 */
public class Menu extends javax.swing.JPanel {

    private Window win;
    private Font origami;
    private Font pencil36;
    private Font pencil48;
    private SoundPlayer soundPlayer;
    
    /**
     * Creates new form Menus
     */
    public Menu(Window win) {
        soundPlayer = new SoundPlayer();
        this.win = win;
        origami = new FontLoader().loadFont(CustomFont.ORIGAMI, 48);
        pencil36 = new FontLoader().loadFont(CustomFont.PENCIL, 36);
        pencil48 = new FontLoader().loadFont(CustomFont.PENCIL, 48);
        initComponents();
        jButton1.addMouseListener(new ControllerHover(pencil36, pencil48));
        jButton2.addMouseListener(new ControllerHover(pencil36, pencil48));
        jButton3.addMouseListener(new ControllerHover(pencil36, pencil48));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(null);

        jLabel1.setFont(origami);
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MORPION");
        jLabel1.setToolTipText("");
        add(jLabel1);
        jLabel1.setBounds(120, 50, 270, 80);

        jButton1.setFont(pencil36);
        jButton1.setText("Jouer");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setIconTextGap(0);
        jButton1.setMaximumSize(new java.awt.Dimension(143, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(143, 23));
        jButton1.setName(""); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(143, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(125, 143, 250, 60);

        jButton2.setFont(pencil36);
        jButton2.setText("Charger une partie");
        jButton2.setActionCommand("CHARGER PARTIE");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(60, 220, 380, 60);

        jButton3.setFont(pencil36);
        jButton3.setText("Quitter");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(143, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(143, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(143, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(130, 300, 250, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Style/img/papier.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        soundPlayer.playSound(CustomSound.PAGE);
        win.setContentPane(new NewGame(win));
        win.pack();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        soundPlayer.playSound(CustomSound.PAGE);
        SwingUtilities.getWindowAncestor(this).dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        soundPlayer.playSound(CustomSound.PAGE);
        win.setContentPane(new LoadGame(win));
        win.pack();
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
