/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHover;
import Controller.ControllerNewGame;
import Style.Font.CustomFont;
import Style.Font.FontLoader;
import java.awt.Font;
import javax.swing.JTextField;

/**
 *
 * @author p1706110
 */
public class NewGame extends javax.swing.JPanel {

    private Window win;
    private Font origami24;
    private Font pencil42;
    private Font pencil32;
    private Font pencil24;
    
    /**
     * Creates new form NewGames
     */
    public NewGame(Window win) {
        origami24 = new FontLoader().loadFont(CustomFont.ORIGAMI, 24);
        pencil42 = new FontLoader().loadFont(CustomFont.PENCIL, 42);
        pencil32 = new FontLoader().loadFont(CustomFont.PENCIL, 32);
        pencil24 = new FontLoader().loadFont(CustomFont.PENCIL, 24);
        this.win = win;
        initComponents();
        this.jButton2.addActionListener(new ControllerNewGame(this));
        this.jButton2.addMouseListener(new ControllerHover(pencil32,pencil42));
    }
    
    public boolean verifNoms(){
        if (!this.jTextField1.getText().equals("") && !this.jTextField2.getText().equals("")) {
            return true;
        }
        return false;
    }

    public Window getWin() {
        return win;
    }
    
    

    public String getjTextField1() {
        return jTextField1.getText();
    }

    public String getjTextField2() {
        return jTextField2.getText();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setRequestFocusEnabled(false);
        setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Style/img/retour.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 80, 71, 46);

        jLabel2.setFont(pencil24);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Joueur 1 :");
        add(jLabel2);
        jLabel2.setBounds(70, 159, 140, 50);

        jLabel3.setFont(pencil24);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Joueur 2 :");
        add(jLabel3);
        jLabel3.setBounds(70, 206, 140, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(222, 175, 162, 24);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(222, 223, 162, 24);

        jButton2.setFont(pencil32);
        jButton2.setText("Commencer");
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(130, 280, 240, 32);

        jLabel1.setFont(origami24);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nouvelle Partie");
        add(jLabel1);
        jLabel1.setBounds(120, 80, 270, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Style/img/papier.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        win.setContentPane(new Menu(win));
        win.pack();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
