/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHover;
import Controller.ControllerReplay;
import Models.partie.Partie;
import Style.Font.CustomFont;
import Style.Font.FontLoader;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Paul
 */
public class Replay extends javax.swing.JPanel {

    private Partie partie;
    private int indexAction = 0; //  0 = pas de case remplie; 1-9 = nb de cases remplies
    private Font pencil28;
    private Font pencil22;
    
    /**
     * Creates new form Replay
     */
    public Replay(Partie partie) {
        pencil28 = new FontLoader().loadFont(CustomFont.PAPER, 38);
        pencil22 = new FontLoader().loadFont(CustomFont.PAPER, 32);
        initComponents();
        this.partie = partie;
        jButton11.addActionListener(new ControllerReplay(this));
        jButton10.addActionListener(new ControllerReplay(this));
        jButton10.addMouseListener(new ControllerHover(pencil22, pencil28));
        jButton11.addMouseListener(new ControllerHover(pencil22, pencil28));
    }
    
    public Partie getPartie(){
        return partie;
    }
    
    public JButton getPrevButton(){
        return jButton11;
    }
    
    public JButton getNextButton(){
        return jButton10;
    }
    
    public ArrayList<JButton> getGameButtons(){
        ArrayList<JButton> gameButtons = new ArrayList();
        gameButtons.add(jButton1);
        gameButtons.add(jButton2);
        gameButtons.add(jButton3);
        gameButtons.add(jButton4);
        gameButtons.add(jButton5);
        gameButtons.add(jButton6);
        gameButtons.add(jButton7);
        gameButtons.add(jButton8);
        gameButtons.add(jButton9);
        return gameButtons;
    }
    
    public int getIndexAction(){
        return indexAction;
    }
    
    public void setIndexAction(int indexAction){
        this.indexAction = indexAction;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(328, 328));
        setMinimumSize(new java.awt.Dimension(328, 328));
        setPreferredSize(new java.awt.Dimension(328, 328));
        setLayout(null);

        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        add(jButton1);
        jButton1.setBounds(43, 21, 75, 75);

        jButton2.setToolTipText("");
        jButton2.setContentAreaFilled(false);
        add(jButton2);
        jButton2.setBounds(124, 21, 75, 75);

        jButton3.setToolTipText("");
        jButton3.setContentAreaFilled(false);
        add(jButton3);
        jButton3.setBounds(205, 21, 75, 75);

        jButton4.setToolTipText("");
        jButton4.setContentAreaFilled(false);
        add(jButton4);
        jButton4.setBounds(43, 102, 75, 75);

        jButton5.setToolTipText("");
        jButton5.setContentAreaFilled(false);
        add(jButton5);
        jButton5.setBounds(124, 102, 75, 75);

        jButton6.setToolTipText("");
        jButton6.setContentAreaFilled(false);
        add(jButton6);
        jButton6.setBounds(205, 102, 75, 75);

        jButton7.setToolTipText("");
        jButton7.setContentAreaFilled(false);
        add(jButton7);
        jButton7.setBounds(43, 183, 75, 75);

        jButton8.setToolTipText("");
        jButton8.setContentAreaFilled(false);
        add(jButton8);
        jButton8.setBounds(124, 183, 75, 75);

        jButton9.setToolTipText("");
        jButton9.setContentAreaFilled(false);
        add(jButton9);
        jButton9.setBounds(205, 183, 75, 75);

        jButton10.setFont(pencil22);
        jButton10.setText(">>");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        add(jButton10);
        jButton10.setBounds(182, 300, 128, 45);

        jButton11.setFont(pencil22);
        jButton11.setText("<<");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        add(jButton11);
        jButton11.setBounds(10, 300, 128, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Style/img/papier.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
