/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHover;
import Controller.ControllerLoadGame;
import Models.Player;
import Style.Font.CustomFont;
import Style.Font.FontLoader;
import database.Connexion;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author p1706110
 */
public class Stats extends javax.swing.JPanel
{
    private DefaultTableModel listeStats;
    private ArrayList<Player> listeJoueurs;
    private Window win;
    private Font origami24;
    private Font pencil32;
    private Font pencil42;
    
    /**
     * Creates new form loadGame
     * @param win
     */
    public Stats(Window win)
    {
        origami24 = new FontLoader().loadFont(CustomFont.ORIGAMI, 22);
        pencil32 = new FontLoader().loadFont(CustomFont.PENCIL, 22);
        pencil42 = new FontLoader().loadFont(CustomFont.PENCIL, 28);
        this.win = win;
        listeStats = new DefaultTableModel();
        listeJoueurs = new ArrayList();
        initComponents();
        loadPlayers();
        
    }
    
    private void loadPlayers(){
        listeStats.addColumn("Pseudo");
        listeStats.addColumn("Parties jouées");
        listeStats.addColumn("Manches gagnées");
        listeStats.addColumn("Manches perdues");
        listeStats.addColumn("Ratio de victoires");
        Connexion co = new Connexion();
        listeJoueurs = co.loadJoueurs();
        for(Player p : listeJoueurs){
            String pseudo = p.getName();
            int partiesTot = p.getNbParties();
            int nbManchesG = p.getNbManchesGag();
            int nbManchesP = p.getNbManchesTot()-p.getNbManchesGag();
            Double ratio = (double) Math.round(((float)nbManchesG/(nbManchesG+nbManchesP)) * 100 * 100.0) / 100.0;
            listeStats.addRow(new Object[]{pseudo,partiesTot,nbManchesG,nbManchesP,ratio+"%"});
        }
        
    }

    public Window getWin() {
        return win;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(origami24);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Statistiques");
        add(jLabel1);
        jLabel1.setBounds(110, 60, 290, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(listeStats);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 130, 500, 270);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Style/img/retour.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 60, 71, 38);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Style/img/papier.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        win.setContentPane(new Menu(win));
        win.pack();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}